#!/usr/bin/env sh

# Règle 8 : par défault, toute action est interdite.
iptables -t filter -P INPUT DROP
iptables -t filter -P OUTPUT DROP
iptables -t filter -P FORWARD DROP

# Règle 2 : autoriser les ping du LAN au WAN, du LAN à la DMZ et de la DMZ au LAN.
iptables -t filter -A FORWARD -p icmp --icmp-type echo-request -s 192.168.100.0/24 -o eth0 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -t filter -A FORWARD -p icmp --icmp-type echo-reply   -d 192.168.100.0/24 -i eth0 -m conntrack --ctstate ESTABLISHED -j ACCEPT

iptables -t filter -A FORWARD -p icmp --icmp-type echo-request -s 192.168.100.0/24 -d 192.168.200.0/24 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -t filter -A FORWARD -p icmp --icmp-type echo-reply   -d 192.168.100.0/24 -s 192.168.200.0/24 -m conntrack --ctstate ESTABLISHED -j ACCEPT

iptables -t filter -A FORWARD -p icmp --icmp-type echo-request -s 192.168.200.0/24 -d 192.168.100.0/24 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -t filter -A FORWARD -p icmp --icmp-type echo-reply   -d 192.168.200.0/24 -s 192.168.100.0/24 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# Règle 1 : autoriser les requêtes DNS du LAN au WAN (UDP & TCP).
iptables -t filter -A FORWARD -p udp -s 192.168.100.0/24 -o eth0 --dport 53 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -t filter -A FORWARD -p udp -d 192.168.100.0/24 -i eth0 --sport 53 -m conntrack --ctstate ESTABLISHED -j ACCEPT

iptables -t filter -A FORWARD -p tcp -s 192.168.100.0/24 -o eth0 --dport 53 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -t filter -A FORWARD -p tcp -d 192.168.100.0/24 -i eth0 --sport 53 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# Règle 3 et 4 : autoriser le traffic du LAN au WAN sur les ports 80, 8080 et 443.
iptables -t filter -A FORWARD -p tcp -s 192.168.100.0/24 -o eth0 --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -t filter -A FORWARD -p tcp -d 192.168.100.0/24 -i eth0 --sport 80 -m conntrack --ctstate ESTABLISHED -j ACCEPT

iptables -t filter -A FORWARD -p tcp -s 192.168.100.0/24 -o eth0 --dport 8080 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -t filter -A FORWARD -p tcp -d 192.168.100.0/24 -i eth0 --sport 8080 -m conntrack --ctstate ESTABLISHED -j ACCEPT

iptables -t filter -A FORWARD -p tcp -s 192.168.100.0/24 -o eth0 --dport 443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -t filter -A FORWARD -p tcp -d 192.168.100.0/24 -i eth0 --sport 443 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# Règle 5 : autoriser le traffic du LAN et WAN vers le serveur de la DMZ sur le port 80.
iptables -t filter -A FORWARD -p tcp -s 192.168.100.0/24 -d 192.168.200.3 --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -t filter -A FORWARD -p tcp -d 192.168.100.0/24 -s 192.168.200.3 --sport 80 -m conntrack --ctstate ESTABLISHED -j ACCEPT

iptables -t filter -A FORWARD -p tcp -i eth0 -d 192.168.200.3 --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -t filter -A FORWARD -p tcp -o eth0 -s 192.168.200.3 --sport 80 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# Règle 6 : autoriser les connections ssh du client LAN au serveur de la DMZ sur le port 22.
iptables -t filter -A FORWARD -p tcp -s 192.168.100.3 -d 192.168.200.3 --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -t filter -A FORWARD -p tcp -d 192.168.100.3 -s 192.168.200.3 --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# Règle 7 : autoriser les connections ssh du client LAN au firewall sur le port 22.
iptables -t filter -A INPUT  -p tcp -s 192.168.100.3 -d 192.168.100.2 --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -t filter -A OUTPUT -p tcp -d 192.168.100.3 -s 192.168.100.2 --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# # Generated by iptables-save v1.6.1 on Thu Mar 28 23:05:56 2019
# *filter
# :INPUT DROP [0:0]
# :FORWARD DROP [0:0]
# :OUTPUT DROP [80:5680]
# -A INPUT -s 192.168.100.3/32 -d 192.168.100.2/32 -p tcp -m tcp --dport 22 -j ACCEPT
# -A FORWARD -s 192.168.100.0/24 -d 192.168.200.0/24 -i eth1 -o eth2 -p icmp -m icmp --icmp-type 8 -j ACCEPT
# -A FORWARD -s 192.168.200.0/24 -d 192.168.100.0/24 -i eth2 -o eth1 -p icmp -m icmp --icmp-type 0 -j ACCEPT
# -A FORWARD -s 192.168.100.0/24 -o eth0 -p icmp -m icmp --icmp-type 8 -j ACCEPT
# -A FORWARD -d 192.168.100.0/24 -i eth0 -p icmp -m icmp --icmp-type 0 -j ACCEPT
# -A FORWARD -s 192.168.200.0/24 -d 192.168.100.0/24 -p icmp -m icmp --icmp-type 8 -j ACCEPT
# -A FORWARD -s 192.168.100.0/24 -d 192.168.200.0/24 -p icmp -m icmp --icmp-type 0 -j ACCEPT
# -A FORWARD -s 192.168.100.0/24 -o eth0 -p udp -m udp --dport 53 -j ACCEPT
# -A FORWARD -d 192.168.100.0/24 -i eth0 -p udp -m udp --sport 53 -j ACCEPT
# -A FORWARD -s 192.168.100.0/24 -o eth0 -p tcp -m tcp --dport 53 -j ACCEPT
# -A FORWARD -d 192.168.100.0/24 -i eth0 -p tcp -m tcp --sport 53 -j ACCEPT
# -A FORWARD -s 192.168.100.0/24 -o eth0 -p tcp -m tcp --dport 80 -j ACCEPT
# -A FORWARD -d 192.168.100.0/24 -i eth0 -p tcp -m tcp --sport 80 -j ACCEPT
# -A FORWARD -s 192.168.100.0/24 -o eth0 -p tcp -m tcp --dport 443 -j ACCEPT
# -A FORWARD -d 192.168.100.0/24 -i eth0 -p tcp -m tcp --sport 443 -j ACCEPT
# -A FORWARD -s 192.168.100.0/24 -o eth0 -p tcp -m tcp --dport 8080 -j ACCEPT
# -A FORWARD -d 192.168.100.0/24 -i eth0 -p tcp -m tcp --sport 8080 -j ACCEPT
# -A FORWARD -s 192.168.100.0/24 -d 192.168.200.3/32 -p tcp -m tcp --dport 80 -j ACCEPT
# -A FORWARD -s 192.168.200.3/32 -d 192.168.100.0/24 -p tcp -m tcp --sport 80 -j ACCEPT
# -A FORWARD -s 192.168.100.3/32 -d 192.168.200.3/32 -p tcp -m tcp --dport 22 -j ACCEPT
# -A FORWARD -s 192.168.200.3/32 -d 192.168.100.3/32 -p tcp -m tcp --sport 22 -j ACCEPT
# -A OUTPUT -s 192.168.100.2/32 -d 192.168.100.3/32 -p tcp -m tcp --sport 22 -j ACCEPT
# COMMIT
# # Completed on Thu Mar 28 23:05:56 2019
# # Generated by iptables-save v1.6.1 on Thu Mar 28 23:05:56 2019
# *nat
# :PREROUTING ACCEPT [441:34599]
# :INPUT ACCEPT [2:144]
# :OUTPUT ACCEPT [24:1710]
# :POSTROUTING ACCEPT [33:2322]
# :DOCKER_OUTPUT - [0:0]
# :DOCKER_POSTROUTING - [0:0]
# -A OUTPUT -d 127.0.0.11/32 -j DOCKER_OUTPUT
# -A POSTROUTING -d 127.0.0.11/32 -j DOCKER_POSTROUTING
# -A POSTROUTING -o eth0 -j MASQUERADE
# -A DOCKER_OUTPUT -d 127.0.0.11/32 -p tcp -m tcp --dport 53 -j DNAT --to-destination 127.0.0.11:36477
# -A DOCKER_OUTPUT -d 127.0.0.11/32 -p udp -m udp --dport 53 -j DNAT --to-destination 127.0.0.11:48126
# -A DOCKER_POSTROUTING -s 127.0.0.11/32 -p tcp -m tcp --sport 36477 -j SNAT --to-source :53
# -A DOCKER_POSTROUTING -s 127.0.0.11/32 -p udp -m udp --sport 48126 -j SNAT --to-source :53
# COMMIT
# # Completed on Thu Mar 28 23:05:56 2019
