version: '3.7'

services:
  wildfly:
    build:
      context: ../../.. # root of the project
      dockerfile: docker/images/wildfly/Dockerfile
    ports:
      - 8080:8080
      - 9990:9990
    volumes:
      - ${PWD}/../../../db/database.sqlite:/db/database.sqlite
      - ${PWD}/../../../target/project-one.war:/opt/jboss/wildfly/standalone/deployments/project-one.war
